# Generated by Django 4.0.2 on 2022-02-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiryuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email_Id', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
    ]
